Sub Group creation added
Elifinanc/ProgrammeDailyStandup pull request #8
Opened 2020-01-27 16:04 UTC by lwolf83

2020-01-27 16:09 UTC, prevostcorentin requested changes
Ca y est presque mais pas encore ! Relis les commentaires et corrige.

2020-01-27 16:09 UTC, prevostcorentin commented on IO.cs
> +                    Console.WriteLine("     {0}", students);
Utilise le caractère spécial `\t` pour faire une tabulation

2020-01-27 16:09 UTC, prevostcorentin commented on IO.cs
> +                Console.WriteLine();
Pourquoi sauter deux lignes ?

2020-01-27 16:09 UTC, prevostcorentin commented on IO.cs
> +        public static List<List<string>> GetGroups(List<string> studentsGroup,int numberOfGroup)
Ta méthode est au mauvais endroit. C'est la classe `StudentShuffler` qui randomise les étudiants, et non la classe `IO` qui est uniquement censée s'occuper de fournir une interface vers le terminal.

2020-01-27 16:42 UTC, lwolf83 commented on IO.cs
> +                    Console.WriteLine("     {0}", students);
Modifié

2020-01-27 16:43 UTC, lwolf83 commented on IO.cs
> +        public static List<List<string>> GetGroups(List<string> studentsGroup,int numberOfGroup)
Fonction déplacée.

2020-01-27 16:47 UTC, lwolf83 reviewed
J'ai fait les 3 modifications.

2020-02-03 15:59 UTC, prevostcorentin reviewed
A propos du découpage en groupe: Tu n'utilisais pas les méthodes `Last` et `Skip` de l'extension `IEnumerable`. De plus le code était compliqué et ça ne fonctionnait pas correctement: le traitement des étudiants restants donnait des groupes où un étudiant était seul.

J'ai réecrit la fonctionnalité en prenant moins de lignes, en une seule méthode et surtout le traitement des étudiants restants ne forme que des groupes et ne laisse aucun étudiant en solitaire (même si c'est un nerd asocial).

Un commentaire explique rapidement le principe. En gros, je crée autant de groupes que nécessaire en découpant mon tableau randomisé, puis une fois fait, si il y a un reste, j'assigne un étudiant restant par groupe.

2020-02-03 15:59 UTC, prevostcorentin commented on StudentShuffler.cs
> +        {
Le code est quand même vachement compliqué. Tu peux réussir à le faire de manière plus simple et lisible avec l'extension Linq:
```C#
shuffledStudents.Take(shuffledStudents.Length / n);
```
Renvoie une liste des `shuffledStudents.Length / n` premiers éléments. 
```C#
shuffledStudents.Skip(shuffledStudents.Length / n);
```
Renvoie une liste des éléments après `shuffledStudents.Length / n` éléments.

En jouant avec ces méthodes tu peux réussir à simplifier.

2020-02-03 15:59 UTC, prevostcorentin commented on StudentShuffler.cs
> +        {
```
tant que currentStudents.Length > 0:
                currentStudents.Length / n == 5;
                currentStudents.Length % n == 1;
                ReturnArray.Add(currentStudents.Take(currentStudents.Length / n));
                currentStudents = currentStudents.Skip(currentStudents.Length / n));
```
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skip?view=netframework-4.8

2020-02-03 15:59 UTC, prevostcorentin commented on Program.cs
>              [Option ('f', "filepath", HelpText = "Provide a filepath")]
Pour que le programme fonctionne il faut **forcément** un fichier contenant les élèves. Conséquemment, l'option 
 `-f/--filepath` doit avoir une valeur par défaut ou être obligatoire.

2020-02-03 16:02 UTC, prevostcorentin approved these changes

2020-02-03 16:03 UTC, merged